import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#9900ce",
        "on-surface": "#ecedf6",
        "on-secondary": "#39004f",
        "error-dim": "#d7383b",
        "primary-fixed": "#00f4fe",
        "on-tertiary-fixed": "#294300",
        "tertiary-container": "#a2f31f",
        "primary-container": "#00f4fe",
        "error-container": "#9f0519",
        "surface-bright": "#282c36",
        "surface-dim": "#0b0e14",
        "tertiary-fixed-dim": "#95e400",
        "surface-container-low": "#10131a",
        outline: "#73757d",
        surface: "#0b0e14",
        "surface-container-lowest": "#000000",
        "secondary-fixed": "#f1c1ff",
        "on-secondary-fixed": "#580078",
        "tertiary-dim": "#95e400",
        "on-error": "#490006",
        secondary: "#d873ff",
        "on-primary": "#006165",
        "on-error-container": "#ffa8a3",
        tertiary: "#bcff5f",
        "primary-dim": "#00e5ee",
        primary: "#a1faff",
        "surface-tint": "#a1faff",
        "tertiary-fixed": "#a2f31f",
        "inverse-on-surface": "#52555c",
        "secondary-dim": "#bc00fb",
        "on-background": "#ecedf6",
        "surface-container-high": "#1c2028",
        error: "#ff716c",
        "primary-fixed-dim": "#00e5ee",
        "surface-container": "#161a21",
        "surface-container-highest": "#22262f",
        "on-primary-container": "#00575b",
        "on-secondary-fixed-variant": "#8400b2",
        "outline-variant": "#45484f",
        "on-tertiary-container": "#365700",
        "on-tertiary-fixed-variant": "#3d6200",
        "on-secondary-container": "#fff5fc",
        "on-primary-fixed-variant": "#006266",
        "secondary-fixed-dim": "#ebadff",
        "inverse-primary": "#006a6e",
        "inverse-surface": "#f9f9ff",
        "surface-variant": "#22262f",
        "on-tertiary": "#3d6100",
        "on-surface-variant": "#a9abb3",
        background: "#0b0e14",
        "on-primary-fixed": "#004346",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        label: ["var(--font-body)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
